smartcontractkit/blockchain-developer-hub

LICENSE

Add license to the respository

---

data/learn.yaml

Fix: Content for learn page

---

data/learn.yaml

fix: copy changes in learn page

---

src/components/NavLink/NavLink.module.css
src/layouts/BlogLayout/BlogLayout.module.css

page bottom link responsive

---

.github/dependabot.yaml

Dependabot yaml file added

---

src/components/Card/Card.jsx
src/components/Card/Card.module.css

added few css props, made some finding

---

data/ecosystem-accordion.yaml
src/components/ExploreMapBanner/ExploreMapBanner.jsx

FIx Ecosystem map link

---

data/build.yaml

Fix bad descriptions

---

data/build.yaml
src/components/Card/Card.jsx

Fix case and style for build section

---

src/components/FloatingButton/FloatingButton.module.css
src/components/NavBar/NavBar.module.css
src/layouts/BlogLayout/BlogLayout.module.css

feat: navbar sticky

---

package-lock.json
src/sections/BuildPageSection/BuildPageSection.module.css
src/sections/LearnCrypto/LearnCrypto.module.css

Hash sign for heading truncated on mobile fixed.

Pr 222/heading hashsign

---

README.md
data/pages/ship.md
package-lock.json
src/styles/MDX.module.css
src/styles/globals.css

table responsiveness and also updated the README file to explain how to add a responsive table to the markdown files.

Fix: table responsiveness and also updated the README file

---

src/components/NoItemPlaceholder/NoItemPlaceholder.jsx
src/components/NoItemPlaceholder/NoItemPlaceholder.module.css
src/components/NoItemPlaceholder/index.js
src/pages/blockchain101/[slug].js
src/sections/BuildPageSection/BuildPageSection.jsx
src/sections/BuildPageSection/BuildPageSection.module.css
src/sections/LearnCrypto/LearnCrypto.jsx
src/sections/LearnCrypto/LearnCrypto.module.css

Placeholder when there is no event or item.

no event or item placeholder

---

src/components/FloatingButton/FloatingButton.module.css
src/components/Overlay/Overlay.module.css

Z index added/increased respectively

fix: Z index added/increased respectively

---

next.config.js

Added Lang attribute to the html through the next config

chore: Lang attribute added to the html

---

src/components/Card/Card.jsx
src/components/NavLink/NavLink.jsx
src/components/Svg/Svg.jsx
src/sections/HomeExplore/HomeExplore.jsx
src/sections/HomePageBanner/HomePageBanner.jsx
src/sections/HomePageBlockchain/HomepageBlockchain.jsx
src/sections/LearnHero/LearnHero.jsx

Replaced object with img tab in Svg component for accessibility purposes.

chore: replaced object with img tag in the Svg component

---

src/components/Card/Card.jsx

fix: Remove title from alt on Card components

---

src/layouts/BlogLayout/BlogLayout.module.css

fix: reduce the left padding of the blog layout

---

public/icons/dropdown-blue.svg
public/icons/dropdown-green.svg
src/components/ArticleHeader/ArticleHeader.module.css
src/components/BlogCustomComponents/BlogHeading.jsx
src/components/FloatingButton/FloatingButton.jsx
src/components/FloatingButton/FloatingButton.module.css
src/layouts/BlogLayout/BlogLayout.jsx
src/layouts/BlogLayout/BlogLayout.module.css
src/styles/MDX.module.css

Resolves: #273 
As a visitor, I would like the Blog layout to be redesigns to have a web 3 look.
NOTE: the branch needs to be merged into a new branch called "redesign" otherwise it will break the live site!
AC:

Redesign blog content

---

src/components/Card/Card.jsx
src/components/Card/Card.module.css
src/components/CardWithLogo/CardWithLogo.jsx
src/components/CardWithLogo/CardWithLogo.module.css
src/components/FloatingButton/FloatingButton.module.css
src/components/Footer/Footer.module.css
src/layouts/BlogLayout/BlogLayout.module.css
src/pages/learn.js
src/sections/HomeExplore/HomeExplore.jsx
src/sections/HomeExplore/HomeExplore.module.css
src/sections/LearnCrypto/LearnCrypto.jsx
src/sections/LearnCrypto/LearnCrypto.module.css
src/sections/LearnHero/LearnHero.jsx
src/sections/LearnHero/LearnHero.module.css
src/styles/globals.css
src/styles/pages/LearnPage.module.css

As a user of the application, I would like the "learn" pages to be redesigned with the new styles
NOTE: the branch needs to be merged into a new branch called "redesign" otherwise it will break the live site!
AC:

chore: learn page completed

---

public/icons/close.svg
src/components/ShareModal/ShareModal.jsx
src/components/ShareModal/ShareModal.module.css

Share modal update

---

src/components/CardWithLogo/CardWithLogo.module.css
src/sections/LearnCrypto/LearnCrypto.module.css
src/sections/LearnHero/LearnHero.module.css

chore: learn page updated

---

src/components/BlogCustomComponents/BlogHeading.jsx
src/components/HeadingHash/HeadingHash.module.css
src/layouts/BlogLayout/BlogLayout.jsx
src/layouts/BlogLayout/BlogLayout.module.css
src/sections/BuildPageSection/BuildPageSection.jsx
src/sections/BuildPageSection/BuildPageSection.module.css
src/styles/MDX.module.css
src/styles/colors.css

https://www.figma.com/file/9eqpfWUrL3gAQ6Royvl75u?node-id=10740:67423#242545354

Blog page update

---

src/components/CardWithArrow/CardWithArrow.module.css

- add spacing between title and icon across all pages  https://www.figma.com/file/9eqpfWUrL3gAQ6Royvl75u?node-id=10739:66318#242518405

chore: updated

---

src/pages/index.js
src/sections/HomePageBanner/HomePageBanner.jsx
src/sections/HomePageBanner/HomePageBanner.module.css
src/sections/HomePageBlockchain/HomepageBlockchain.module.css
src/styles/globals.css
src/styles/pages/HomePage.module.css

chore: update completed

---

src/components/TutorialCard/TutorialCard.jsx
src/components/TutorialCard/TutorialCard.module.css

- add more space between the author and title https://www.figma.com/file/9eqpfWUrL3gAQ6Royvl75u?node-id=10739:66318#242521655
- Hover effect

chore: tutorial card updated

---

data/pages/blockchain101/blockchain.md

Update report link

---

src/sections/HomePageBanner/HomePageBanner.jsx

Update hero title verbiage

---

data/build.yaml
src/sections/HomePageImproveSkills/HomePageImproveSkills.jsx

Update section names

---

data/learn.yaml

Update learn.yaml with 32 hour course

---

src/components/BlogCustomComponents/BlogLink.jsx
src/components/BlogCustomComponents/index.js

Resolves: #358
Hyperlinks open in new page for the ship page for following sections:
Stack
Examples and Inspiration

Hyperlinks open in new page

---

src/components/ExploreMapBanner/ExploreMapBannerWithoutAccordion.jsx

Resolves: #360
Change Engineer to Developer on the 2nd CTA

Ecosystem Text Change

---

data/build.yaml
data/case-studies.yaml
data/navbarLinks.yaml
src/components/NavBar/NavBar.module.css
src/components/PagePagination/PagePagination.jsx
src/components/PagePagination/PagePagination.module.css
src/pages/case-studies/index.js
src/sections/BuildPageSection/BuildPageSection.jsx
src/sections/BuildPageSection/BuildPageSection.module.css
src/styles/pages/BuildPage.module.css

AC:
moved case studies in build to its own page, created yaml file for housing case studies

Case studies page

---

data/internal-case-studies-data.js
src/sections/BuildPageSection/BuildPageSection.jsx

used `.replace` instead of `.replaceAll`
inspiration from [FIX: replaceAll() is not a Function In JavaScript](https://dev.to/shivampawar/fix-replaceall-is-not-a-function-in-javascript-3klp)

attempt to fix build fail

---

data/ecosystem-accordion.yaml
data/navbarLinks.yaml
data/pages/ship.md
src/components/ExploreMapBanner/ExploreMapBannerWithAccordion.jsx
src/components/ExploreMapBanner/ExploreMapBannerWithoutAccordion.jsx
src/pages/ecosystem-map.js
src/stories/MarkdownStyle/MarkdownContent.md

Update link of blockchain Ecosystem 

---

data/learn.yaml

update learn resources
